#!/usr/bin/env bash
# Regenerates .agents/skills/ from .claude/skills/, the single source.
# OpenSpec's own skills (openspec-*) are generated by `openspec init`/`openspec update`
# in both places and are left alone; customize OpenSpec through openspec/config.yaml.
set -euo pipefail
root="$(git rev-parse --show-toplevel)"
src="$root/.claude/skills"
dst="$root/.agents/skills"
mkdir -p "$dst"

for dir in "$dst"/*/; do
  name="$(basename "$dir")"
  [[ "$name" == openspec-* ]] && continue
  [[ -d "$src/$name" ]] || rm -rf "$dir"
done

for dir in "$src"/*/; do
  name="$(basename "$dir")"
  [[ "$name" == openspec-* ]] && continue
  rm -rf "${dst:?}/$name"
  cp -R "$dir" "$dst/$name"
done
echo "synced $(find "$src" -mindepth 1 -maxdepth 1 -type d ! -name 'openspec-*' | wc -l) skill(s) into .agents/skills"
